"""
File Manager Module
===================
Handles file validation, output directory management, and Markdown report
generation for the LLVM Optimization Explorer.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import TYPE_CHECKING

from diff_viewer import compute_diff, diff_to_markdown
from statistics import StageStats, stats_to_markdown

if TYPE_CHECKING:
    pass


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

class FileValidationError(Exception):
    """Raised when an input file fails validation."""


def validate_c_file(path: str | Path) -> Path:
    """Validate that *path* points to a readable ``.c`` file.

    Returns the resolved ``Path`` on success, or raises
    ``FileValidationError`` with a descriptive message.
    """
    p = Path(path).resolve()

    if not p.exists():
        raise FileValidationError(f"File not found: {p}")
    if not p.is_file():
        raise FileValidationError(f"Not a regular file: {p}")
    if p.suffix.lower() != ".c":
        raise FileValidationError(
            f"Expected a .c file, got '{p.suffix}': {p}\n"
            "This tool accepts C source files only."
        )
    if not os.access(p, os.R_OK):
        raise FileValidationError(f"Permission denied (cannot read): {p}")

    return p


# ---------------------------------------------------------------------------
# Output directory
# ---------------------------------------------------------------------------

def ensure_output_dir(base_dir: str | Path) -> Path:
    """Create the output directory if it does not exist.  Returns the Path."""
    out = Path(base_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    return out


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------

def generate_report(
    stage_names: list[str],
    stage_ir_contents: list[str],
    stage_reconstructed_c: list[str],
    stage_stats: list[StageStats],
    original_c: str,
    output_path: str | Path,
) -> Path:
    """Generate a comprehensive Markdown optimization report.

    The report includes:
    * Original C source
    * Overall statistics table
    * Per-stage IR diffs
    * Per-stage reconstructed C diffs
    * Summary of total instruction reduction

    Returns the path to the written file.
    """
    out = Path(output_path)
    sections: list[str] = []

    # Title
    sections.append("# LLVM Optimization Report\n")
    sections.append(
        "Auto-generated by **LLVM Optimization Explorer**.\n"
    )

    # Original C source
    sections.append("## Original C Source\n")
    sections.append(f"```c\n{original_c}\n```\n")

    # Statistics table
    sections.append("## Optimization Statistics\n")
    sections.append(stats_to_markdown(stage_names, stage_stats))
    sections.append("")

    # Summary
    if len(stage_stats) >= 2:
        first = stage_stats[0]
        last = stage_stats[-1]
        removed = first.instructions - last.instructions
        pct = (removed / first.instructions * 100) if first.instructions else 0
        sections.append("## Summary\n")
        sections.append(
            f"* **Instructions removed**: {removed} "
            f"({pct:.1f}% reduction)\n"
        )
        sections.append(
            f"* **Calls removed**: {first.calls - last.calls}\n"
        )
        sections.append(
            f"* **Branches removed**: {first.branches - last.branches}\n"
        )
        sections.append(
            f"* **Blocks removed**: {first.blocks - last.blocks}\n"
        )

    # Per-stage IR diffs
    sections.append("## Per-Stage IR Changes\n")
    for i in range(1, len(stage_names)):
        diff_lines = compute_diff(
            stage_ir_contents[i - 1],
            stage_ir_contents[i],
            before_label=stage_names[i - 1],
            after_label=stage_names[i],
        )
        sections.append(
            diff_to_markdown(stage_names[i - 1], stage_names[i], diff_lines)
        )

    # Per-stage reconstructed C diffs
    sections.append("## Per-Stage Reconstructed C Changes\n")
    for i in range(1, len(stage_names)):
        diff_lines = compute_diff(
            stage_reconstructed_c[i - 1],
            stage_reconstructed_c[i],
            before_label=f"{stage_names[i - 1]} (C)",
            after_label=f"{stage_names[i]} (C)",
        )
        sections.append(
            diff_to_markdown(
                f"{stage_names[i - 1]} (C)",
                f"{stage_names[i]} (C)",
                diff_lines,
            )
        )

    # Final reconstructed C
    sections.append("## Final Reconstructed C (after DCE)\n")
    sections.append(f"```c\n{stage_reconstructed_c[-1]}\n```\n")

    out.write_text("\n".join(sections), encoding="utf-8")
    return out
